-- Seed sample tours
insert into public.tours (
  title,
  slug,
  description,
  short_description,
  destination,
  duration_days,
  duration_nights,
  price,
  max_participants,
  difficulty_level,
  category,
  image_url,
  included_items,
  excluded_items,
  itinerary,
  is_featured,
  is_active
) values
(
  'Cape Coast Castle Heritage Tour',
  'cape-coast-castle-heritage-tour',
  'Embark on a profound journey through Ghana''s history with our Cape Coast Castle Heritage Tour. This immersive experience takes you through the doors of no return, where you''ll walk in the footsteps of ancestors and learn about the transatlantic slave trade. Our expert guides provide deep cultural context and historical insights that bring this important history to life.',
  'Explore the historic Cape Coast Castle and learn about Ghana''s pivotal role in world history',
  'Cape Coast, Ghana',
  1,
  0,
  150.00,
  15,
  'Easy',
  'Heritage',
  '/placeholder.svg?height=600&width=800',
  array['Professional tour guide', 'Transportation', 'Entry fees', 'Lunch', 'Bottled water'],
  array['Personal expenses', 'Tips and gratuities', 'Travel insurance'],
  '{"day1": {"title": "Full Day Heritage Experience", "activities": ["Morning departure from Accra", "Guided tour of Cape Coast Castle", "Visit to the Door of No Return", "Traditional Ghanaian lunch", "Explore the surrounding fishing village", "Return to Accra by evening"]}}'::jsonb,
  true,
  true
),
(
  'Kakum National Park Canopy Walk',
  'kakum-national-park-canopy-walk',
  'Experience the breathtaking beauty of Ghana''s rainforest from above on our Kakum National Park Canopy Walk. Walk across seven suspension bridges suspended 40 meters above the forest floor, offering spectacular views of the pristine tropical rainforest. This eco-tourism adventure combines thrilling heights with educational insights about Ghana''s diverse ecosystem and conservation efforts.',
  'Walk among the treetops on Africa''s longest canopy walkway through pristine rainforest',
  'Kakum National Park, Ghana',
  1,
  0,
  120.00,
  20,
  'Moderate',
  'Eco-Tourism',
  '/placeholder.svg?height=600&width=800',
  array['Park entry fees', 'Professional guide', 'Canopy walk access', 'Transportation', 'Lunch', 'Drinking water'],
  array['Personal items', 'Camera fees', 'Tips'],
  '{"day1": {"title": "Rainforest Adventure", "activities": ["Early morning departure", "Guided nature walk through the forest", "Canopy walkway experience", "Wildlife spotting", "Local cuisine lunch", "Visit to butterfly sanctuary", "Return journey"]}}'::jsonb,
  true,
  true
),
(
  'Ashanti Kingdom Cultural Experience',
  'ashanti-kingdom-cultural-experience',
  'Immerse yourself in the rich cultural heritage of the Ashanti Kingdom with this comprehensive 3-day tour. Visit the Manhyia Palace Museum, explore traditional craft villages, witness kente weaving, and learn about the golden stool. Experience authentic Ashanti hospitality, traditional ceremonies, and the vibrant markets of Kumasi, the cultural heart of Ghana.',
  'Discover the traditions, crafts, and royal heritage of Ghana''s Ashanti Kingdom',
  'Kumasi, Ghana',
  3,
  2,
  450.00,
  12,
  'Easy',
  'Cultural',
  '/placeholder.svg?height=600&width=800',
  array['Accommodation (2 nights)', 'All meals', 'Professional cultural guide', 'Transportation', 'Museum entry fees', 'Craft workshop participation'],
  array['International flights', 'Visa fees', 'Personal purchases', 'Optional activities'],
  '{"day1": {"title": "Arrival and Manhyia Palace", "activities": ["Welcome and orientation", "Visit Manhyia Palace Museum", "Traditional welcome ceremony", "Evening cultural performance"]}, "day2": {"title": "Craft Villages and Markets", "activities": ["Bonwire kente weaving village", "Ntonso adinkra stamping village", "Kejetia Market exploration", "Traditional drumming workshop"]}, "day3": {"title": "Okomfo Anokye Sword and Departure", "activities": ["Visit sacred sword site", "Prempeh II Jubilee Museum", "Souvenir shopping", "Departure"]}}'::jsonb,
  true,
  true
),
(
  'Volta Region Waterfalls Adventure',
  'volta-region-waterfalls-adventure',
  'Discover the natural wonders of Ghana''s Volta Region on this 2-day adventure. Hike through lush forests to reach the majestic Wli Waterfalls, the highest waterfall in West Africa. Cool off in natural pools, explore traditional mountain villages, and experience the hospitality of the Ewe people. This tour combines physical activity with cultural immersion and natural beauty.',
  'Hike to West Africa''s highest waterfall and explore scenic Volta Region villages',
  'Volta Region, Ghana',
  2,
  1,
  280.00,
  15,
  'Challenging',
  'Adventure',
  '/placeholder.svg?height=600&width=800',
  array['Accommodation (1 night)', 'All meals', 'Professional guide', 'Transportation', 'Hiking equipment', 'Entry fees'],
  array['Personal gear', 'Travel insurance', 'Tips'],
  '{"day1": {"title": "Journey to Wli", "activities": ["Departure from Accra", "Scenic drive through Volta Region", "Arrival at Wli", "Afternoon hike to lower falls", "Swimming in natural pools", "Check-in at eco-lodge", "Dinner and stargazing"]}, "day2": {"title": "Upper Falls and Cultural Experience", "activities": ["Early morning hike to upper falls", "Village tour", "Traditional craft demonstration", "Lunch with local family", "Return to Accra"]}}'::jsonb,
  false,
  true
),
(
  'Mole National Park Safari',
  'mole-national-park-safari',
  'Experience Ghana''s premier wildlife destination on this 3-day safari adventure. Mole National Park is home to elephants, antelopes, warthogs, baboons, and over 300 bird species. Enjoy guided walking safaris, 4x4 game drives, and the unique opportunity to get close to wild elephants at watering holes. This tour offers authentic African safari experiences in Ghana''s largest wildlife refuge.',
  'Encounter wild elephants and diverse wildlife in Ghana''s premier national park',
  'Mole National Park, Ghana',
  3,
  2,
  550.00,
  10,
  'Moderate',
  'Wildlife',
  '/placeholder.svg?height=600&width=800',
  array['Park accommodation (2 nights)', 'All meals', 'Professional safari guide', 'Walking safaris', '4x4 game drives', 'Park fees', 'Round-trip transport'],
  array['Drinks at lodge', 'Optional activities', 'Personal expenses', 'Tips'],
  '{"day1": {"title": "Arrival and Evening Safari", "activities": ["Scenic drive to Mole", "Check-in at safari lodge", "Orientation briefing", "Sunset game drive", "Dinner overlooking savanna"]}, "day2": {"title": "Full Day Safari", "activities": ["Dawn walking safari", "Breakfast", "Morning game drive", "Lunch and rest", "Afternoon walking safari", "Evening at elephant watering hole"]}, "day3": {"title": "Morning Safari and Departure", "activities": ["Early morning game drive", "Breakfast", "Final wildlife viewing", "Departure to Accra"]}}'::jsonb,
  true,
  true
),
(
  'Accra City Heritage and Food Tour',
  'accra-city-heritage-food-tour',
  'Experience the vibrant capital city with our comprehensive Accra Heritage and Food Tour. Visit Independence Square, the Kwame Nkrumah Memorial Park, and explore the historic Jamestown district. Sample authentic Ghanaian street food, visit bustling markets, and learn about Ghana''s journey to independence. This tour perfectly blends history, culture, and culinary delights.',
  'Discover Accra''s landmarks, colonial history, and vibrant street food scene',
  'Accra, Ghana',
  1,
  0,
  100.00,
  20,
  'Easy',
  'Cultural',
  '/placeholder.svg?height=600&width=800',
  array['Professional guide', 'Transportation', 'Food tastings', 'Entrance fees', 'Bottled water'],
  array['Additional meals', 'Personal shopping', 'Tips'],
  '{"day1": {"title": "Full Day City Experience", "activities": ["Independence Square", "Kwame Nkrumah Mausoleum", "Jamestown walking tour", "Street food tasting", "Makola Market exploration", "Arts Centre visit", "Labadi Beach sunset"]}}'::jsonb,
  false,
  true
);
